### ISSUE TITLE
regtest.py needs tweak to run successfully in python 3

### ISSUE THREAD

**Issue by andrewschultz** [erkyrath/plotex#1]
The solution is pretty simple. Python is stricter about print '...' and only allows print ('...') now.

So I was just able to replace with a regex, and the script interprets again.

This is something I could do by committing a fork, but I'm just generally worried about lousing things up, and I wanted to check if there's anything special you needed me to do or check.

**Comment by erkyrath** [comment]
Done. (Required a little more work than just the print statements.)
