### ISSUE TITLE
RegTest: UnicodeDecodeError error with Glulxe and Glulxercise

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/plotex#10]
I'm not sure what's at fault here, but I'm getting an error when running Glulxercise in Glulxe/Cheapglk in RegTest (latest of each) in Linux ([test file](https://github.com/curiousdannii/emglken/blob/master/tests/glulxercise.ulx.regtest)):

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 16315: invalid continuation byte
```

I'd assumed this would be one of the string tests, but that offset looks like the stack operations test?

**Comment by erkyrath** [comment]
You need to use the -u argument to glulxe-cheapglk for Unicode output.

**Comment by curiousdannii** [comment]
Ahh, interesting. I'd assumed because I saw in my terminal some non-ascii ("up-case �䴵4.") that it had been handling unicode already. But that must have just been my terminal trying to make the best of what it was given, and now I see the correct text is "up-case ãäδεд." With -u RegTest passes. Thanks!
