### ISSUE TITLE
Broken Pipe in RemGlk mode

### ISSUE THREAD

**Issue by curiousdannii** [erkyrath/plotex#11]
When trying to run this Linux binary [glulxercise.zip](https://github.com/erkyrath/plotex/files/6558263/glulxercise.zip) with [glulxercise.ulx.regtest](https://raw.githubusercontent.com/curiousdannii/if-decompiler/master/tests/glulxercise.ulx.regtest), I'm getting a broken pipe error.

```
python3 ./regtest.py -i glulxercise glulxercise.ulx.regtest -r
```

I added logging, which shows the pipe is breaking at line 626, which is right when the initial data is sent into the app.

```
BrokenPipeError: [Errno 32] Broken pipe
ERROR:__main__:[Errno 32] Broken pipe
Traceback (most recent call last):
  File "./regtest.py", line 1154, in run
    gamestate.initialize()
  File "./regtest.py", line 626, in initialize
    self.infile.write((cmd+'\n').encode())
BrokenPipeError: [Errno 32] Broken pipe
```

If I manually run glulxercise and send the init event then it seems to work correctly. I can't work out what is different that causes it to break with regtes.t.

Any ideas? I can send you the full sources if it would help.

**Comment by curiousdannii** [comment]
Here are the sources
[glulxercise-source.zip](https://github.com/erkyrath/plotex/files/6563489/glulxercise-source.zip)

To compile against remglk
```
cmake -DGlkLibPath=../remglk -S . -B ./output
```

Oh, and I was compiling with Clang not GCC, which probably doesn't matter?

**Comment by curiousdannii** [comment]
I thought I'd found the cause, but actually it doesn't fix it. Cheapglk doesn't complain if an extra argument is passed, but Remglk does. I can add back the storyfile argument... and after doing so it's still getting a broken pipe.

Edit: and I've fixed it. I had also been passing `-u` to Cheapglk, and needed to take that out for Remglk.

**Comment by erkyrath** [comment]
Ok good.

**Comment by curiousdannii** [comment]
I would've worked this out a lot quicker if the output had been printed with verbose mode. Do you know why it's not echoing output from the very beginning?

**Comment by erkyrath** [comment]
You mean regtest.py? It defaults to non-verbose mode because that's how I use it. 99% of the time, I'm re-running a regression test list to verify that there are no regressions. So I want to see a column of test names with no error messages. The output of each test would be noise.

**Comment by curiousdannii** [comment]
I meant that even when you switch verbose mode on it doesn't show anything from an interpreter erroring and halting right at the beginning.

**Comment by erkyrath** [comment]
Oh, I see what you mean. I'll take a look at that.

**Comment by erkyrath** [comment]
It's not obvious how to improve this. In this situation, the interpreter exits without ever reading input, so regtest.py crashes in GameStateRemGlk.initialize(). (The first self.infile.write() causes this exception.) It never reaches the point of reading from proc.stdout.
