### ISSUE TITLE
Regtest: help to make it work on my French game (encodings)?

### ISSUE THREAD

**Issue by stormi** [erkyrath/plotex#16]
Hi!

I'm trying to use Regtest, which looks like what I need to test my inform 6 IFs while I modify them or when I change the underyling libraries.

I know well about encodings in general, but not really how it works at the interpreter level.

Right now, my chain is:
- French I6 libraries encoded in utf-8
- Game sources encoded in utf-8
- Compilation to `.ulx` with `!% -Cu` on top of the main source file
- `glulxe` compiled with `cheapglk` as an interpreter

To my surprise, the output from glulxe is encoded in what seems to be `ISO-8859-1`.

This doesn't please Regtest which expects `utf-8` (as I would, too):
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 20: invalid continuation byte
```

Do you see anything obvious I may have missed?

**Comment by curiousdannii** [comment]
You have to pass `-u` to cheapglk for it to use UTF-8.

**Comment by stormi** [comment]
Thanks, this was so simple :).
