### ISSUE TITLE
Transcript output differs between `cheap` and `rem` modes

### ISSUE THREAD

**Issue by stormi** [erkyrath/plotex#19]
In `cheap` mode, there is a space after the prompt, which looks nice:

```
> examine thing
The thing is stuff.
```

In `rem` mode, no space:
```
>examine thing
The thing is stuff.
```

This causes a large diff on my outputs after switching from `cheap` to `rem`.

**Comment by erkyrath** [comment]
The rem mode matches the game's actual display; the cheap mode does not.

But I didn't expect the regtest output to itself be stored and used for validation! There's no intention to keep it stable between releases or modes.
