### ISSUE TITLE
regtest.py chokes on unicode

### ISSUE THREAD

**Issue by angstsmurf** [erkyrath/plotex#3]
When running tests, regtest.py kept giving me “UnicodeDecodeError: 'ascii' codec can't decode byte” whenever the game output any non-ascii characters. I tried using both Git and Glulxe compiled with RemGlk.

After reading [this](http://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte), I added 

```
reload(sys)  
sys.setdefaultencoding('utf8')
```

after the "import" lines, and now it seems to work fine. OS X 10.11.6, Python 2.7.10.

**Comment by erkyrath** [comment]
It's correct under Python3, so I don't want to mess that up. I'll see if there's a better way to do this.

**Comment by erkyrath** [comment]
Fixed.

**Comment by angstsmurf** [comment]
Thanks!
